[tool.poetry]
name = "codex"
version = "0.1.0"
description = ""
authors = ["Nemesis <lorenzo.balugani@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
neomodel = "^4.0.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
